### ISSUE TITLE
Not working with github atom based releases feed

### ISSUE THREAD

**Issue by trivigy** [suhlig/concourse-rss-resource#3]
This is the error I am getting on the resource page.
```
resource script '/opt/resource/check []' failed: exit status 1

stderr:
Error processing feed: undefined method `channel' for #<RSS::Atom::Feed:0x0000556c86a7e2a0>
```

**Comment by suhlig** [comment]
Thanks for the report. Can you provide a URL that is not working for you? 

I have to admin that the testing of ATOM feeds is pretty poor yet. But GitHub seems important enough to invest.

**Comment by trivigy** [comment]
@suhlig sorry bud, I posted that in 2018. Haven't used comcourse since. Probably good to close this issue.
